### ISSUE TITLE
Evaluate public and private methods

### ISSUE THREAD

**Issue by gagdiez** [flmel/evaluator#8]
Private methods are very useful, specially in the context of callbacks to cross-contract calls. We need people to understand the difference between:

- Private methods
- Public methods
- Public methods that can only be called by the same smart contract (methods mark as private)

**Comment by flmel** [comment]
We have decided to move the additional (integration checks) to a separate repo which could be found [here](https://github.com/flmel/evaluator-integration-checks/)
